### ISSUE TITLE
Book car to drive from PDX to SEA in

### ISSUE THREAD

**Issue by parisba** [thesecretlab/presentations#1]
There is no car booked.

Steps to reproduce:
*check tripit for car booking after OSCON

*observe there is no car booked

*get stuck in PDX; become alternative book seller

*put a bird on it

Expected result:
*check tripit for car booking after OSCON

*observe that we have a car booked

*arrive at SEA

**Comment by chrisjrn** [comment]
Will attend to momentarily.

--Chris

Sent from a mobile device, whilst mobile.
On Apr 23, 2012 3:30 PM, "Paris Buttfield-Addison" <
reply@reply.github.com>
wrote:

**Comment by chrisjrn** [comment]
Multiple simulations performed, behaviour is not reproducible as there is currently no path that will result in us being in PDX at the time. Issue #2 has been assigned to @parisba for prompt resolution.
